
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/main.py'],
    pathex=[r'/Users/yuclaw/.openclaw/workspace/合同对比助手/src'],
    binaries=[],
    datas=[
        ('src/core', 'core'),
        ('src/ui', 'ui'),
        ('src/utils', 'utils'),
    ],
    hiddenimports=[
        # Word 处理
        'docx',
        'docx.opc',
        'docx.opc.oxml',
        'docx.oxml',
        'docx.oxml.ns',
        'docx.text',
        'docx.styles',
        'docx.enum',
        'docx.shared',
        'docx.oxml.simpletypes',
        'docx.oxml.ns',
        'docx.enum.style',
        'docx.enum.table',
        'docx.enum.section',
        'docx.enum.text',
        'docx.formatting',
        
        # Excel 处理
        'openpyxl',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'openpyxl.cell',
        'openpyxl.styles',
        'openpyxl.utils',
        'openpyxl.reader',
        'openpyxl.writer',
        
        # PyQt6
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.sip',
        
        # 项目模块 - 使用点号格式
        'core',
        'core.doc_comparator',
        'core.__init__',
        'ui',
        'ui.main_window',
        'ui.__init__',
        'utils',
        'utils.logger',
        'utils.error_handler',
        'utils.pdf_handler',
        'utils.updater',
        'utils.styles',
        'utils.__init__',
        
        # 标准库
        'logging',
        'logging.handlers',
        'json',
        're',
        'tempfile',
        'datetime',
        'os',
        'sys',
        'webbrowser',
        'collections',
        'encodings',
        'encodings.utf_8',
        'hashlib',
        'io',
        'difflib',
        'traceback',
        'subprocess',
        'shutil',
        'zipfile',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'numpy',
        'PIL',
        'pillow',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='合同对比助手',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
